import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  tr: {
    'nav.navigation': 'Navigasyon',
    'nav.explore': 'Sitede gezinmek için bir bölüm seçin',
    'nav.home': 'Ana Sayfa',
    'nav.about': 'Hakkımda',
    'nav.experience': 'Deneyim',
    'nav.technologies': 'Teknolojiler',
    'nav.portfolio': 'Portföy',
    'nav.contact': 'İletişim',
    'nav.getInTouch': 'İletişime Geç',
    'hero.subtitle': 'Yazılım Geliştirici & Siber Güvenlik Çözümleri',
    'hero.description': 'Modern web teknolojileri ve siber güvenlik alanında uzmanlaşmış, yenilikçi çözümler üreten bir yazılım geliştiriciyim. İşletmelerin dijital dönüşümünde güvenli ve etkili siber güvenlik çözümleri sunuyorum.',
    'hero.webDevelopment': 'Modern Web Geliştirme & Tasarım',
    'hero.integrationAutomation': 'Sistem Entegrasyonu & Otomasyon',
    'hero.cybersecurity': 'Siber Güvenlik & Penetrasyon Testleri',
    'hero.downloadCV': 'CV İndir',
    'hero.viewProjects': 'Projeleri Gör',
    'about.title': 'Hakkımda',
    'about.greeting': 'Merhaba, ben Sina Toprak Güleç!',
    'about.intro1': 'Ben ',
    'about.intro2': 'teknoloji tutkunu bir Full Stack geliştirici ve siber güvenlik uzmanıyım. ',
    'about.intro3': 'İstanbul\'da yaşıyor, modern web teknolojileri ve güvenlik sistemleri alanında projeler geliştiriyorum.',
    'about.intro4': '5+ yıllık deneyimim boyunca ',
    'about.intro5': 'birçok başarılı projede yer aldım. ',
    'about.intro6': 'Özellikle ',
    'about.intro7': ' teknolojilerinde uzmanlaştım ve işletmelerin dijital dönüşümlerine katkı sağlıyorum.',
    'about.intro8': 'Amacım, güvenli, kullanıcı dostu ve performanslı web uygulamaları geliştirerek, müşterilerimin başarısına ortak olmaktır.',
    'about.workingStyle': 'Çalışma Tarzım',
    'about.detailOriented': 'Detaylara Odaklı Yaklaşım',
    'about.fastProblemSolving': 'Hızlı Problem Çözme',
    'about.techPassion': 'Teknoloji Tutkusu',
    'about.continuousLearning': 'Sürekli Öğrenme',
    'experience.title': 'Deneyim',
    'experience.subtitle': 'Profesyonel yolculuğum ve başarılarım',
    'experience.currentPosition': 'Mevcut Pozisyon',
    'experience.keyAchievements': 'Başlıca Başarılar',
    'experience.technologies': 'Teknolojiler',
    'experience.years': 'yıl',
    'experience.present': 'Devam Ediyor',
    'technologies.title': 'Teknolojiler',
    'technologies.subtitle': 'Kullandığım teknolojiler ve araçlar',
    'technologies.frontend': 'Frontend',
    'technologies.backend': 'Backend',
    'technologies.database': 'Veritabanı',
    'technologies.tools': 'Araçlar & DevOps',
    'technologies.toolsDatabase': 'Araçlar & Veritabanı',
    'portfolio.title': 'Portföy',
    'portfolio.subtitle': 'Seçili projelerim ve çalışmalarım',
    'portfolio.description': 'Gerçek projelerim ve çalışmalarımdan örnekler',
    'portfolio.viewProject': 'Projeyi Gör',
    'portfolio.liveDemo': 'Canlı Demo',
    'portfolio.viewDetails': 'Detayları Gör',
    'portfolio.details': 'Detaylar',
    'portfolio.demo': 'Demo',
    'portfolio.featured': 'Öne Çıkan',
    'portfolio.completed': 'Tamamlandı',
    'portfolio.inProgress': 'Devam Ediyor',
    'portfolio.planning': 'Planlama',
    'portfolio.technologies': 'Teknolojiler',
    'portfolio.projectImage': 'Proje Görseli',
    'portfolio.client': 'Müşteri',
    'portfolio.year': 'Yıl',
    'portfolio.viewDemo': 'Demo Gör',
    'portfolio.github': 'GitHub',
    'portfolio.projectDetails': 'Proje Detayları',
    'projects.documentVerification.title': 'Belge Doğrulama Sistemi',
    'projects.documentVerification.category': 'Web Uygulaması',
    'projects.documentVerification.description': 'Akredite kurumlar için belge yönetimi ve doğrulama işlemlerini kolaylaştıran full-stack web uygulaması.',
    'projects.documentVerification.client': 'TÜRKAK',
    'projects.documentVerification.longDescription': '.NET Core Web API (backend), React ve TypeScript (frontend) ile geliştirilen, veritabanı olarak Microsoft SQL Server kullanılan full-stack bir web uygulamasıdır. Bu platform, akredite kurumların müşteri verilerini yönetmesini, teknik belgeleri yükleyip takip etmesini ve kayıtları harici API\'ler aracılığıyla doğrulamasını sağlar. Sistem; rol bazlı kullanıcı erişimi, belge yönetimi, sertifika-cihaz ilişkilendirme gibi özellikleri destekler ve TÜRKAK\'ın resmi RESTful API servisleriyle entegre çalışır.',
    'projects.hotelBooking.title': 'Otel Rezervasyon Sistemi',
    'projects.hotelBooking.category': 'Desktop Uygulama',
    'projects.hotelBooking.description': 'Otel rezervasyonu ve yönetimi için geliştirilmiş kapsamlı desktop uygulaması',
    'projects.hotelBooking.client': 'Ders Projesi',
    'projects.hotelBooking.longDescription': 'C# Windows Forms ile geliştirilen otel yönetim sistemidir. Sistemde müşteri giriş-çıkış işlemleri, oda ekleme ve düzenleme, personel ekleme-çıkarma modülleri bulunmaktadır. MSSQL Server veritabanı ile güvenli veri saklama sağlar.',
    'projects.hospitalManagement.title': 'Hastane Yönetim Sistemi',
    'projects.hospitalManagement.category': 'Yönetim Sistemi',
    'projects.hospitalManagement.description': 'Hastane operasyonlarını dijitalleştiren kapsamlı yönetim sistemi',
    'projects.hospitalManagement.client': 'Sağlık Kurumu',
    'projects.hospitalManagement.longDescription': 'Hastane operasyonlarını dijitalleştiren ve optimize eden kapsamlı yönetim sistemi. Hasta kayıtları, randevu yönetimi ve tıbbi süreçleri kapsıyor.',
    'projects.ecommerceAnalytics.title': 'E-Ticaret Analitik Paneli',
    'projects.ecommerceAnalytics.category': 'Analitik Dashboard',
    'projects.ecommerceAnalytics.description': 'E-ticaret verilerini analiz eden gerçek zamanlı dashboard',
    'projects.ecommerceAnalytics.client': 'E-Ticaret Şirketi',
    'projects.ecommerceAnalytics.longDescription': 'E-ticaret verilerini analiz eden ve görselleştiren gerçek zamanlı dashboard. Satış trendleri, müşteri davranışları ve performans metrikleri.',
    'contact.title': 'İletişim',
    'contact.subtitle': 'Yazılım geliştirici ve siber güvenlik çözümleri',
    'contact.description': 'Yazılım geliştirme projeleriniz ve siber güvenlik çözümleriniz hakkında konuşmak veya iş birliği için benimle iletişime geçebilirsiniz.',
    'contact.name': 'Adınız',
    'contact.email': 'E-posta',
    'contact.message': 'Mesajınız',
    'contact.send': 'Mesaj Gönder',
    'loading.title': 'Güvenli Bağlantı Kuruluyor',
    'loading.preparing': 'Sistem hazırlanıyor',
    'loading.encryption': '> Şifreleme protokolleri aktifleştiriliyor...',
    'loading.connection': '> Güvenli bağlantı kuruluyor...',
    'loading.interface': '> Kullanıcı arayüzü yükleniyor...',
    'footer.subtitle': 'Yazılım Geliştirici & Siber Güvenlik Çözümleri',
    'footer.copyright': '© 2025 Sina Toprak Güleç. Tüm hakları saklıdır.'
  },
  en: {
    'nav.navigation': 'Navigation',
    'nav.explore': 'Select a section to explore the site',
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.experience': 'Experience',
    'nav.technologies': 'Technologies',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Contact',
    'nav.getInTouch': 'Get In Touch',
    'hero.subtitle': 'Software Developer & Cybersecurity Solutions',
    'hero.description': 'I am a software developer specialized in modern web technologies and cybersecurity, creating innovative solutions. I provide secure and effective cybersecurity solutions for businesses digital transformation.',
    'hero.webDevelopment': 'Modern Web Development & Design',
    'hero.integrationAutomation': 'System Integration & Automation',
    'hero.cybersecurity': 'Cybersecurity & Penetration Testing',
    'hero.downloadCV': 'Download CV',
    'hero.viewProjects': 'View Projects',
    'about.title': 'About Me',
    'about.greeting': 'Hello, I am Sina Toprak Güleç!',
    'about.intro1': 'I am a ',
    'about.intro2': 'technology passionate Full Stack developer and cybersecurity expert. ',
    'about.intro3': 'I live in Istanbul and develop projects in modern web technologies and security systems.',
    'about.intro4': 'During my 5+ years of experience, ',
    'about.intro5': 'I have been involved in many successful projects. ',
    'about.intro6': 'I especially specialize in ',
    'about.intro7': ' technologies and contribute to the digital transformation of businesses.',
    'about.intro8': 'My goal is to be a partner in my clients success by developing secure, user-friendly and performant web applications.',
    'about.workingStyle': 'My Working Style',
    'about.detailOriented': 'Detail-Oriented Approach',
    'about.fastProblemSolving': 'Fast Problem Solving',
    'about.techPassion': 'Technology Passion',
    'about.continuousLearning': 'Continuous Learning',
    'experience.title': 'Experience',
    'experience.subtitle': 'My professional journey and achievements',
    'experience.currentPosition': 'Current Position',
    'experience.keyAchievements': 'Key Achievements',
    'experience.technologies': 'Technologies',
    'experience.years': 'years',
    'experience.present': 'Present',
    'technologies.title': 'Technologies',
    'technologies.subtitle': 'Technologies and tools I use',
    'technologies.frontend': 'Frontend',
    'technologies.backend': 'Backend',
    'technologies.database': 'Database',
    'technologies.tools': 'Tools & DevOps',
    'technologies.toolsDatabase': 'Tools & Database',
    'portfolio.title': 'Portfolio',
    'portfolio.subtitle': 'My selected projects and works',
    'portfolio.description': 'Examples from my real projects and works',
    'portfolio.viewProject': 'View Project',
    'portfolio.liveDemo': 'Live Demo',
    'portfolio.viewDetails': 'View Details',
    'portfolio.details': 'Details',
    'portfolio.demo': 'Demo',
    'portfolio.featured': 'Featured',
    'portfolio.completed': 'Completed',
    'portfolio.inProgress': 'In Progress',
    'portfolio.planning': 'Planning',
    'portfolio.technologies': 'Technologies',
    'portfolio.projectImage': 'Project Image',
    'portfolio.client': 'Client',
    'portfolio.year': 'Year',
    'portfolio.viewDemo': 'View Demo',
    'portfolio.github': 'GitHub',
    'portfolio.projectDetails': 'Project Details',
    'projects.documentVerification.title': 'Document Verification System',
    'projects.documentVerification.category': 'Web Application',
    'projects.documentVerification.description': 'Full-stack web application that facilitates document management and verification processes for accredited institutions.',
    'projects.documentVerification.client': 'TURKAK',
    'projects.documentVerification.longDescription': 'A full-stack web application developed with .NET Core Web API (backend), React and TypeScript (frontend), using Microsoft SQL Server as database. This platform enables accredited institutions to manage customer data, upload and track technical documents, and verify records through external APIs. The system supports features such as role-based user access, document management, certificate-device association and integrates with TURKAK\'s official RESTful API services.',
    'projects.hotelBooking.title': 'Hotel Booking System',
    'projects.hotelBooking.category': 'Desktop Application',
    'projects.hotelBooking.description': 'Comprehensive desktop application developed for hotel reservation and management',
    'projects.hotelBooking.client': 'Course Project',
    'projects.hotelBooking.longDescription': 'A hotel management system developed with C# Windows Forms. The system includes customer check-in/check-out operations, room adding and editing, staff hiring and removal modules. Provides secure data storage with MSSQL Server database.',
    'projects.hospitalManagement.title': 'Hospital Management System',
    'projects.hospitalManagement.category': 'Management System',
    'projects.hospitalManagement.description': 'Comprehensive management system that digitalizes hospital operations',
    'projects.hospitalManagement.client': 'Healthcare Institution',
    'projects.hospitalManagement.longDescription': 'Comprehensive management system that digitalizes and optimizes hospital operations. It covers patient records, appointment management and medical processes.',
    'projects.ecommerceAnalytics.title': 'E-Commerce Analytics Dashboard',
    'projects.ecommerceAnalytics.category': 'Analytics Dashboard',
    'projects.ecommerceAnalytics.description': 'Real-time dashboard that analyzes e-commerce data',
    'projects.ecommerceAnalytics.client': 'E-Commerce Company',
    'projects.ecommerceAnalytics.longDescription': 'Real-time dashboard that analyzes and visualizes e-commerce data. Sales trends, customer behavior and performance metrics.',
    'contact.title': 'Contact',
    'contact.subtitle': 'Software developer and cybersecurity solutions',
    'contact.description': 'You can contact me to discuss your software development projects and cybersecurity solutions or for collaboration.',
    'contact.name': 'Your Name',
    'contact.email': 'Email',
    'contact.message': 'Your Message',
    'contact.send': 'Send Message',
    'loading.title': 'Establishing Secure Connection',
    'loading.preparing': 'Preparing system',
    'loading.encryption': '> Activating encryption protocols...',
    'loading.connection': '> Establishing secure connection...',
    'loading.interface': '> Loading user interface...',
    'footer.subtitle': 'Software Developer & Cybersecurity Solutions',
    'footer.copyright': '© 2025 Sina Toprak Güleç. All rights reserved.'
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('tr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[Language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
