import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  tr: {
    'nav.navigation': 'Navigasyon',
    'nav.explore': 'Sitede gezinmek için bir bölüm seçin',
    'nav.home': 'Ana Sayfa',
    'nav.about': 'Hakkımda',
    'nav.experience': 'Deneyim',
    'nav.technologies': 'Teknolojiler',
    'nav.portfolio': 'Portföy',
    'nav.contact': 'İletişim',
    'nav.getInTouch': 'İletişime Geç',
    'hero.subtitle': 'Yazılım Geliştirici & Siber Güvenlik Çözümleri',
    'hero.description': 'Modern web teknolojileri ve siber güvenlik alanında kendini geliştirmiş, yeni fikirlere açık ve yenilikçi çözümler üreten bir geliştiriciyim. Hedefim, işletmelerin dijital dönüşüm yolculuklarında güvenilir ve etkili çözümlerle yanlarında olmaktır.',
    'hero.webDevelopment': 'Modern Web Geliştirme & Tasarım',
    'hero.integrationAutomation': 'Sistem Entegrasyonu & Otomasyon',
    'hero.cybersecurity': 'Siber Güvenlik & Penetrasyon Testleri',
    'hero.downloadCV': 'CV İndir',
    'hero.viewProjects': 'Projeleri Gör',
    'about.title': 'Hakkımda',
    'about.greeting': 'Merhaba, ben Sina Toprak Güleç!',
    'about.intro1': 'Teknolojiye olan ilgim neredeyse dokuz yaşıma kadar dayanıyor. Çocukken gördüğüm her yeni teknolojiyi merakla kurcalamayı ve incelemeyi çok severdim. İstanbul Bilgi Üniversitesi\'nde Siber Güvenlik önlisansımı tamamladım, şu anda ise Işık Üniversitesi Yönetim Bilişim Sistemleri bölümünde 4. sınıf öğrencisiyim.',
    'about.intro2': 'Yazılıma olan ilgim, kullandığım oyunlar ve programlar karşısında "Acaba bunlar nasıl yapılıyor?" sorusunu kendime sormamla başladı. O günden bu yana elimden geldiğince kendimi geliştirmeye, yeni teknolojileri anlamaya ve uyum sağlamaya devam ediyorum.',
    'about.intro3': 'Benim için yazılım sadece bir meslek değil, aynı zamanda bir merak ve tutkudur.',
    'about.intro4': '',
    'about.intro5': '',
    'about.intro6': '',
    'about.intro7': '',
    'about.intro8': '',
    'about.workingStyle': 'Çalışma Tarzım',
    'about.detailOriented': 'Detaylara Odaklı Yaklaşım',
    'about.fastProblemSolving': 'Hızlı Problem Çözme',
    'about.techPassion': 'Teknoloji Tutkusu',
    'about.continuousLearning': 'Sürekli Öğrenme',
    'experience.title': 'Deneyim',
    'experience.subtitle': 'Profesyonel yolculuğum ve başarılarım',
    'experience.currentPosition': 'Mevcut Pozisyon',
    'experience.keyAchievements': 'Başlıca Başarılar',
    'experience.technologies': 'Teknolojiler',
    'experience.years': 'yıl',
    'experience.present': 'Devam Ediyor',
    'technologies.title': 'Teknolojiler',
    'technologies.subtitle': 'Kullandığım teknolojiler ve araçlar',
    'technologies.description': 'Bu teknolojiler ve araçlar, modern web uygulamaları geliştirmek ve siber güvenlik çözümleri sunmak için kullandığım temel araçlardır.',
    'technologies.frontend': 'Frontend',
    'technologies.backend': 'Backend',
    'technologies.database': 'Veritabanı',
    'technologies.tools': 'Araçlar & DevOps',
    'technologies.toolsDatabase': 'Araçlar & Veritabanı',
    'portfolio.title': 'Portföy',
    'portfolio.subtitle': 'Seçili projelerim ve çalışmalarım',
    'portfolio.description': 'Gerçek projelerim ve çalışmalarımdan örnekler',
    'portfolio.viewProject': 'Projeyi Gör',
    'portfolio.liveDemo': 'Canlı Demo',
    'portfolio.viewDetails': 'Detayları Gör',
    'portfolio.details': 'Detaylar',
    'portfolio.demo': 'Demo',
    'portfolio.featured': 'Öne Çıkan',
    'portfolio.completed': 'Tamamlandı',
    'portfolio.inProgress': 'Devam Ediyor',
    'portfolio.planning': 'Planlama',
    'portfolio.technologies': 'Teknolojiler',
    'portfolio.projectImage': 'Proje Görseli',
    'portfolio.client': 'Müşteri',
    'portfolio.year': 'Yıl',
    'portfolio.viewDemo': 'Demo Gör',
    'portfolio.github': 'GitHub',
    'portfolio.projectDetails': 'Proje Detayları',
    'portfolio.imageError': 'Resim yüklenemedi',
    'projects.documentVerification.title': 'Belge Doğrulama Sistemi',
    'projects.documentVerification.category': 'Web Uygulaması',
    'projects.documentVerification.description': 'Akredite kurumlar için belge yönetimi ve doğrulama işlemlerini kolaylaştıran full-stack web uygulaması.',
    'projects.documentVerification.client': 'TÜRKAK',
    'projects.documentVerification.longDescription': '.NET Core Web API (backend), React ve TypeScript (frontend) ile geliştirilen, veritabanı olarak Microsoft SQL Server kullanılan full-stack bir web uygulamasıdır. Bu platform, akredite kurumların müşteri verilerini yönetmesini, teknik belgeleri yükleyip takip etmesini ve kayıtları harici API\'ler aracılığıyla doğrulamasını sağlar. Sistem; rol bazlı kullanıcı erişimi, belge yönetimi, sertifika-cihaz ilişkilendirme gibi özellikleri destekler ve TÜRKAK\'ın resmi RESTful API servisleriyle entegre çalışır.',
    'projects.hotelBooking.title': 'Otel Rezervasyon Sistemi',
    'projects.hotelBooking.category': 'Desktop Uygulama',
    'projects.hotelBooking.description': 'Otel rezervasyonu ve yönetimi için geliştirilmiş kapsamlı desktop uygulaması',
    'projects.hotelBooking.client': 'Ders Projesi',
    'projects.hotelBooking.longDescription': 'C# Windows Forms ile geliştirilen otel yönetim sistemidir. Sistemde müşteri giriş-çıkış işlemleri, oda ekleme ve düzenleme, personel ekleme-çıkarma modülleri bulunmaktadır. MSSQL Server veritabanı ile güvenli veri saklama sağlar.',
    'projects.hospitalManagement.title': 'Hastane Yönetim Sistemi',
    'projects.hospitalManagement.category': 'Yönetim Sistemi',
    'projects.hospitalManagement.description': 'Hastane operasyonlarını dijitalleştiren kapsamlı yönetim sistemi',
    'projects.hospitalManagement.client': 'Sağlık Kurumu',
    'projects.hospitalManagement.longDescription': 'Hastane operasyonlarını dijitalleştiren ve optimize eden kapsamlı yönetim sistemi. Hasta kayıtları, randevu yönetimi ve tıbbi süreçleri kapsıyor.',
    'projects.ecommerceAnalytics.title': 'E-Ticaret Analitik Paneli',
    'projects.ecommerceAnalytics.category': 'Analitik Dashboard',
    'projects.ecommerceAnalytics.description': 'E-ticaret verilerini analiz eden gerçek zamanlı dashboard',
    'projects.ecommerceAnalytics.client': 'E-Ticaret Şirketi',
    'projects.ecommerceAnalytics.longDescription': 'E-ticaret verilerini analiz eden ve görselleştiren gerçek zamanlı dashboard. Satış trendleri, müşteri davranışları ve performans metrikleri.',
    'projects.fileServer.title': 'File Server - Dosya Yönetim Sistemi',
    'projects.fileServer.category': 'Full-Stack Web Uygulaması',
    'projects.fileServer.description': 'FastAPI ve React kullanılarak geliştirilmiş, kullanıcı dostu arayüzü ile drag & drop dosya yükleme, hiyerarşik klasör yapısı ve gerçek zamanlı dosya işlemleri sunan modern cloud dosya yönetim platformu',
    'projects.fileServer.client': 'Kişisel Proje',
    'projects.fileServer.longDescription': 'FastAPI (backend) ve React (frontend) kullanılarak geliştirilmiş modern dosya yönetim sistemi. Drag & drop dosya yükleme, hiyerarşik klasör yapısı, gerçek zamanlı progress bar, dosya önizleme ve güvenli dosya işlemleri içerir. PostgreSQL veritabanı ile Docker containerization desteği sunar.',
    'contact.title': 'İletişim',
    'contact.subtitle': 'Yazılım geliştirici ve siber güvenlik çözümleri',
    'contact.description': 'Yazılım geliştirme projeleriniz ve siber güvenlik çözümleriniz hakkında konuşmak veya iş birliği için benimle iletişime geçebilirsiniz.',
    'contact.name': 'Adınız',
    'contact.email': 'E-posta',
    'contact.subject': 'Konu',
    'contact.message': 'Mesajınız',
    'contact.send': 'Mesaj Gönder',
    'contact.formTitle': 'Mesaj Gönderin',
    'contact.namePlaceholder': 'Adınız ve soyadınız (max 50 karakter)',
    'contact.emailPlaceholder': 'email@example.com',
    'contact.subjectPlaceholder': 'Mesajınızın konusu (max 100 karakter)',
    'contact.messagePlaceholder': 'Mesajınızı buraya yazın... (min 10, max 1000 karakter)',
    'contact.sending': 'Gönderiliyor...',
    'contact.sendMessage': 'Mesaj Gönder',
    'contact.minChars': 'En az',
    'contact.moreChars': 'karakter daha',
    'contact.sufficient': '✓ Yeterli',
    'contact.charCount': 'karakter',
    'contact.contactInfo': 'İletişim Bilgileri',
    'contact.rateLimit': 'Çok hızlı mesaj gönderiyorsunuz.',
    'contact.rateLimitWait': 'dakika sonra tekrar deneyin.',
    'contact.nameMinLength': 'Ad soyad en az 2 karakter olmalıdır',
    'contact.subjectMinLength': 'Konu en az 3 karakter olmalıdır',
    'contact.messageMinLength': 'Mesaj en az 10 karakter olmalıdır',
    'contact.invalidEmail': 'Geçerli bir e-posta adresi girin',
    'contact.spamDetected': 'Mesajınız spam olarak algılandı, lütfen farklı bir içerik yazın',
    'contact.successMessage': 'Mesajınız başarıyla gönderildi! En kısa sürede yanıtlayacağım.',
    'contact.errorFallback': 'Lütfen e-posta ile direkt iletişime geçin: toprakgulec34@gmail.com',
    'contact.emailTitle': 'E-posta',
    'contact.githubTitle': 'GitHub',
    'contact.linkedinTitle': 'LinkedIn',
    'contact.instagramTitle': 'Instagram',
    'hero3d.securityMonitor': 'Security Monitor',
    'hero3d.firewall': 'Firewall',
    'hero3d.sslTls': 'SSL/TLS',
    'hero3d.intrusionDetection': 'Intrusion Detection',
    'hero3d.codeEditor': 'Code Editor',
    'hero3d.terminal': 'Terminal',
    'loading.title': 'Güvenli Bağlantı Kuruluyor',
    'loading.preparing': 'Sistem hazırlanıyor',
    'loading.encryption': '> Şifreleme protokolleri aktifleştiriliyor...',
    'loading.connection': '> Güvenli bağlantı kuruluyor...',
    'loading.interface': '> Kullanıcı arayüzü yükleniyor...',
    'footer.subtitle': 'Yazılım Geliştirici & Siber Güvenlik Çözümleri',
    'footer.copyright': '© 2025 Sina Toprak Güleç. Tüm hakları saklıdır.'
  },
  en: {
    'nav.navigation': 'Navigation',
    'nav.explore': 'Select a section to explore the site',
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.experience': 'Experience',
    'nav.technologies': 'Technologies',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Contact',
    'nav.getInTouch': 'Get In Touch',
    'hero.subtitle': 'Software Developer & Cybersecurity Solutions',
    'hero.description': 'I am a developer who has improved himself in modern web technologies and cybersecurity, open to new ideas and producing innovative solutions. My goal is to be by their side with reliable and effective solutions in businesses\' digital transformation journeys.',
    'hero.webDevelopment': 'Modern Web Development & Design',
    'hero.integrationAutomation': 'System Integration & Automation',
    'hero.cybersecurity': 'Cybersecurity & Penetration Testing',
    'hero.downloadCV': 'Download CV',
    'hero.viewProjects': 'View Projects',
    'about.title': 'About Me',
    'about.greeting': 'Hello, I am Sina Toprak Güleç!',
    'about.intro1': 'My interest in technology dates back to almost nine years old. As a child, I loved curiously tinkering with and examining every new technology I saw. I completed my Cybersecurity associate degree at Istanbul Bilgi University, and currently I am a 4th year student in the Management Information Systems department at Işık University.',
    'about.intro2': 'My interest in software started with asking myself "I wonder how these are made?" in front of the games and programs I used. Since that day, I continue to improve myself as much as I can, understand new technologies and adapt to them.',
    'about.intro3': 'For me, software is not just a profession, but also a curiosity and passion.',
    'about.intro4': '',
    'about.intro5': '',
    'about.intro6': '',
    'about.intro7': '',
    'about.intro8': '',
    'about.workingStyle': 'My Working Style',
    'about.detailOriented': 'Detail-Oriented Approach',
    'about.fastProblemSolving': 'Fast Problem Solving',
    'about.techPassion': 'Technology Passion',
    'about.continuousLearning': 'Continuous Learning',
    'experience.title': 'Experience',
    'experience.subtitle': 'My professional journey and achievements',
    'experience.currentPosition': 'Current Position',
    'experience.keyAchievements': 'Key Achievements',
    'experience.technologies': 'Technologies',
    'experience.years': 'years',
    'experience.present': 'Present',
    'technologies.title': 'Technologies',
    'technologies.subtitle': 'Technologies and tools I use',
    'technologies.description': 'These technologies and tools are the core instruments I use to develop modern web applications and provide cybersecurity solutions.',
    'technologies.frontend': 'Frontend',
    'technologies.backend': 'Backend',
    'technologies.database': 'Database',
    'technologies.tools': 'Tools & DevOps',
    'technologies.toolsDatabase': 'Tools & Database',
    'portfolio.title': 'Portfolio',
    'portfolio.subtitle': 'My selected projects and works',
    'portfolio.description': 'Examples from my real projects and works',
    'portfolio.viewProject': 'View Project',
    'portfolio.liveDemo': 'Live Demo',
    'portfolio.viewDetails': 'View Details',
    'portfolio.details': 'Details',
    'portfolio.demo': 'Demo',
    'portfolio.featured': 'Featured',
    'portfolio.completed': 'Completed',
    'portfolio.inProgress': 'In Progress',
    'portfolio.planning': 'Planning',
    'portfolio.technologies': 'Technologies',
    'portfolio.projectImage': 'Project Image',
    'portfolio.client': 'Client',
    'portfolio.year': 'Year',
    'portfolio.viewDemo': 'View Demo',
    'portfolio.github': 'GitHub',
    'portfolio.projectDetails': 'Project Details',
    'portfolio.imageError': 'Image failed to load',
    'projects.documentVerification.title': 'Document Verification System',
    'projects.documentVerification.category': 'Web Application',
    'projects.documentVerification.description': 'Full-stack web application that facilitates document management and verification processes for accredited institutions.',
    'projects.documentVerification.client': 'TURKAK',
    'projects.documentVerification.longDescription': 'A full-stack web application developed with .NET Core Web API (backend), React and TypeScript (frontend), using Microsoft SQL Server as database. This platform enables accredited institutions to manage customer data, upload and track technical documents, and verify records through external APIs. The system supports features such as role-based user access, document management, certificate-device association and integrates with TURKAK\'s official RESTful API services.',
    'projects.hotelBooking.title': 'Hotel Booking System',
    'projects.hotelBooking.category': 'Desktop Application',
    'projects.hotelBooking.description': 'Comprehensive desktop application developed for hotel reservation and management',
    'projects.hotelBooking.client': 'Course Project',
    'projects.hotelBooking.longDescription': 'A hotel management system developed with C# Windows Forms. The system includes customer check-in/check-out operations, room adding and editing, staff hiring and removal modules. Provides secure data storage with MSSQL Server database.',
    'projects.hospitalManagement.title': 'Hospital Management System',
    'projects.hospitalManagement.category': 'Management System',
    'projects.hospitalManagement.description': 'Comprehensive management system that digitalizes hospital operations',
    'projects.hospitalManagement.client': 'Healthcare Institution',
    'projects.hospitalManagement.longDescription': 'Comprehensive management system that digitalizes and optimizes hospital operations. It covers patient records, appointment management and medical processes.',
    'projects.ecommerceAnalytics.title': 'E-Commerce Analytics Dashboard',
    'projects.ecommerceAnalytics.category': 'Analytics Dashboard',
    'projects.ecommerceAnalytics.description': 'Real-time dashboard that analyzes e-commerce data',
    'projects.ecommerceAnalytics.client': 'E-Commerce Company',
    'projects.ecommerceAnalytics.longDescription': 'Real-time dashboard that analyzes and visualizes e-commerce data. Sales trends, customer behavior and performance metrics.',
    'projects.fileServer.title': 'File Server - File Management System',
    'projects.fileServer.category': 'Full-Stack Web Application',
    'projects.fileServer.description': 'Modern cloud file management platform built with FastAPI and React, featuring user-friendly drag & drop file uploads, hierarchical folder structure, and real-time file operations',
    'projects.fileServer.client': 'Personal Project',
    'projects.fileServer.longDescription': 'Modern file management system developed with FastAPI (backend) and React (frontend). Features drag & drop file upload, hierarchical folder structure, real-time progress bar, file preview and secure file operations. Includes PostgreSQL database with Docker containerization support.',
    'contact.title': 'Contact',
    'contact.subtitle': 'Software developer and cybersecurity solutions',
    'contact.description': 'You can contact me to discuss your software development projects and cybersecurity solutions or for collaboration.',
    'contact.name': 'Your Name',
    'contact.email': 'Email',
    'contact.subject': 'Subject',
    'contact.message': 'Your Message',
    'contact.send': 'Send Message',
    'contact.formTitle': 'Send Message',
    'contact.namePlaceholder': 'Your name and surname (max 50 characters)',
    'contact.emailPlaceholder': 'email@example.com',
    'contact.subjectPlaceholder': 'Subject of your message (max 100 characters)',
    'contact.messagePlaceholder': 'Write your message here... (min 10, max 1000 characters)',
    'contact.sending': 'Sending...',
    'contact.sendMessage': 'Send Message',
    'contact.minChars': 'At least',
    'contact.moreChars': 'more characters',
    'contact.sufficient': '✓ Sufficient',
    'contact.charCount': 'characters',
    'contact.contactInfo': 'Contact Information',
    'contact.rateLimit': 'You are sending messages too quickly.',
    'contact.rateLimitWait': 'minutes later try again.',
    'contact.nameMinLength': 'Name and surname must be at least 2 characters',
    'contact.subjectMinLength': 'Subject must be at least 3 characters',
    'contact.messageMinLength': 'Message must be at least 10 characters',
    'contact.invalidEmail': 'Please enter a valid email address',
    'contact.spamDetected': 'Your message was detected as spam, please write different content',
    'contact.successMessage': 'Your message has been sent successfully! I will respond as soon as possible.',
    'contact.errorFallback': 'Please contact me directly via email: toprakgulec34@gmail.com',
    'contact.emailTitle': 'Email',
    'contact.githubTitle': 'GitHub',
    'contact.linkedinTitle': 'LinkedIn',
    'contact.instagramTitle': 'Instagram',
    'hero3d.securityMonitor': 'Security Monitor',
    'hero3d.firewall': 'Firewall',
    'hero3d.sslTls': 'SSL/TLS',
    'hero3d.intrusionDetection': 'Intrusion Detection',
    'hero3d.codeEditor': 'Code Editor',
    'hero3d.terminal': 'Terminal',
    'loading.title': 'Establishing Secure Connection',
    'loading.preparing': 'Preparing system',
    'loading.encryption': '> Activating encryption protocols...',
    'loading.connection': '> Establishing secure connection...',
    'loading.interface': '> Loading user interface...',
    'footer.subtitle': 'Software Developer & Cybersecurity Solutions',
    'footer.copyright': '© 2025 Sina Toprak Güleç. All rights reserved.'
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('tr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[Language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
